### ISSUE TITLE
Repair broken tooltip pattern

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-pattern-library#20]
Christine made a bunch of fixes to the tooltips in https://github.com/18F/fec-cms/pull/1452 that should be integrated to the pattern library component so that the working version is visible and useable here.

Current broken state:
https://fec-pattern-library.app.cloud.gov/components/detail/tooltips.html
![screen shot 2017-11-07 at 1 47 00 pm](https://user-images.githubusercontent.com/11636908/32511575-300e9558-c3c2-11e7-9c0f-2519442c5b67.png)

**Comment by xtine** [comment]
In updating to circle, I think it fixed itself:
<img width="449" alt="screen shot 2017-11-22 at 2 57 20 pm" src="https://user-images.githubusercontent.com/24054/33151481-88817bd6-cf95-11e7-91ee-e3ba06215ccb.png">

**Comment by jenniferthibault** [comment]
The best issues are the ones that fix themselves. Looks right to me, thanks!
