### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-pattern-library#21]
In order to allow designers to share and review existing icons, repair the display so that they show up:

<img width="1219" alt="screen shot 2017-11-13 at 10 48 03 am" src="https://user-images.githubusercontent.com/11636908/32734468-20fff4b0-c860-11e7-8ffd-7cae9fcf35c8.png">

https://fec-pattern-library.app.cloud.gov/docs/icons.html

**Comment by xtine** [comment]
Going to work on a script on `fec-cms` that will generate an up to date icon template to drop into the pattern library documentation component.
