### ISSUE TITLE
Identify first half of patterns that need changes (in individual GitHub issues) 

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-pattern-library#47]
What we're after:
There may be GitHub issues that create a need for changes or additions to the pattern library. We need to Identify these and add them to library.

- [ ] Finish review of GitHub issues.

**Comment by jenniferthibault** [comment]
I'll update the following list as issues are filed for each pattern:
- [x] Accordions — #55
- [ ] Banner
- [ ] Breadcrumbs
- [ ] Buttons
- [ ] Callout
- [ ] Card icons
- [ ] Contact items
- [ ] Cycle select
- [ ] Documents
- [ ] Figures
- [ ] Filters
- [ ] Footer
- [ ] Header
- [ ] Hero

**Comment by jenniferthibault** [comment]
All components in the list above that need updates or changes now have new issues to track that work specifically.

Closing!
