### ISSUE TITLE
Write/update "how to use" notes for first half of existing patterns in library

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-pattern-library#48]
What we're after:
In order for designers and front end developers to use the pattern library efficiently we need to Write/update the "how to use" notes for existing patterns in library 

- [x] For each pattern in the live pattern library site, there are instructions on how and when to use each pattern.

**Comment by jenniferthibault** [comment]
Adding notes as needed to the following components:

- [x] Accordions
- [ ] Banner
- [x] Breadcrumbs
- [x] Buttons
- [x] Callout
- [x] Card icons
- [ ] Contact items
- [ ] Cycle select
- [ ] Documents
- [ ] Figures
- [ ] Filters
- [ ] Footer
- [ ] Header
- [ ] Hero

**Comment by jenniferthibault** [comment]
Notes have been added via PR #54 — this issue will be closed once that's merged in.
