### ISSUE TITLE
Move to a new CI/CD system

### ISSUE THREAD

**Issue by hollyallen** [18F/fec-pattern-library#9]
This repository has been using Travis CI, however access to Travis CI is now turning off. When you need to use this repository again, convert it to a CI/CD system which is in the ITSP such as Circle CI.

**Comment by ccostino** [comment]
@xtine should we schedule a time to pair on this soon with a couple of FEC folks?

**Comment by xtine** [comment]
@ccostino: yes absolutely, after we figure out circleci to get dev to serve up front-end assets first!

**Comment by ccostino** [comment]
I'm going to move this to sprint 4.3; it seems like we might be able to finally tackle it then!

**Comment by ccostino** [comment]
We're moving this to 4.4 on account of folks' outages and annual review work.

**Comment by ccostino** [comment]
We finally have this moved over!  Thanks again, @xtine, and a huge thank you to @jeremiak for all of the extra help in making this possible!
